/* AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand */
import type { IconManifest, IconListItem } from "./_types";
import { FALLBACK_ICON_ID } from "./_types";

export const ICON_MANIFESTS: IconManifest[] = [
  {
    "id": "bilibili",
    "label": "Bilibili",
    "labelZh": "哔哩哔哩",
    "file": "/icons/bilibili.svg"
  },
  {
    "id": "discord",
    "label": "Discord",
    "labelZh": "Discord",
    "file": "/icons/discord.svg"
  },
  {
    "id": "email",
    "label": "Email",
    "labelZh": "邮箱",
    "file": "/icons/email.svg",
    "aliases": [
      "mail"
    ]
  },
  {
    "id": "facebook",
    "label": "Facebook",
    "labelZh": "Facebook",
    "file": "/icons/facebook.svg"
  },
  {
    "id": "github",
    "label": "GitHub",
    "labelZh": "GitHub",
    "file": "/icons/github.svg"
  },
  {
    "id": "instagram",
    "label": "Instagram",
    "labelZh": "Instagram",
    "file": "/icons/instagram.svg"
  },
  {
    "id": "link",
    "label": "Link",
    "labelZh": "链接",
    "file": "/icons/link.svg"
  },
  {
    "id": "linkedin",
    "label": "LinkedIn",
    "labelZh": "LinkedIn",
    "file": "/icons/linkedin.svg"
  },
  {
    "id": "reddit",
    "label": "Reddit",
    "labelZh": "Reddit",
    "file": "/icons/reddit.svg"
  },
  {
    "id": "rss",
    "label": "RSS",
    "labelZh": "RSS",
    "file": "/icons/rss.svg"
  },
  {
    "id": "telegram",
    "label": "Telegram",
    "labelZh": "Telegram",
    "file": "/icons/telegram.svg"
  },
  {
    "id": "tiktok",
    "label": "TikTok",
    "labelZh": "TikTok",
    "file": "/icons/tiktok.svg"
  },
  {
    "id": "twitch",
    "label": "Twitch",
    "labelZh": "Twitch",
    "file": "/icons/twitch.svg"
  },
  {
    "id": "website",
    "label": "Website",
    "labelZh": "网站",
    "file": "/icons/website.svg",
    "aliases": [
      "globe"
    ]
  },
  {
    "id": "weibo",
    "label": "Weibo",
    "labelZh": "微博",
    "file": "/icons/weibo.svg"
  },
  {
    "id": "x",
    "label": "X",
    "labelZh": "X",
    "file": "/icons/x.svg",
    "aliases": [
      "twitter"
    ]
  },
  {
    "id": "xiaohongshu",
    "label": "Xiaohongshu",
    "labelZh": "小红书",
    "file": "/icons/xiaohongshu.svg"
  },
  {
    "id": "youtube",
    "label": "YouTube",
    "labelZh": "YouTube",
    "file": "/icons/youtube.svg"
  }
] as IconManifest[];

export const ICON_IDS: string[] = ICON_MANIFESTS.map((m) => m.id);

export const ICON_ALIASES: Record<string, string> = {
  "mail": "email",
  "globe": "website",
  "twitter": "x"
};

export function listIcons(): IconListItem[] {
  return ICON_MANIFESTS.map((m) => ({
    id: m.id,
    label: m.label,
    labelZh: m.labelZh,
    file: m.file,
  }));
}

export function getIcon(id: string | undefined | null): IconManifest | null {
  if (!id) return null;
  const found = ICON_MANIFESTS.find((m) => m.id === id);
  return found ?? null;
}

export { FALLBACK_ICON_ID };
