/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand */
import type { ThemeListItem, ThemeManifest } from "./_types";
import { FALLBACK_THEME_ID } from "./_types";

export const THEME_MANIFESTS: ThemeManifest[] = [
  {
    "id": "anthropic",
    "name": "Anthropic Art",
    "nameZh": "Anthropic 插画风",
    "description": "Editorial paper feel — oat page, ivory notes, clay accent, serif type, thick ink strokes, no shadow",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": true
    }
  },
  {
    "id": "apple",
    "name": "Apple",
    "nameZh": "Apple 风格",
    "description": "Apple.com product marketing — solid cool-gray canvas, SF stack, 28px tiles, pill CTAs, first-link primary blue",
    "version": 3,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": true
    }
  },
  {
    "id": "aurora",
    "name": "Aurora",
    "nameZh": "极光",
    "description": "Northern lights default — cool teal–indigo primary, soft radial aurora canvas, dreamy elevation",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "hono-old",
    "name": "Hono Classic",
    "nameZh": "Hono 经典",
    "description": "Linear/Vercel-style dark — near-black canvas, sharp indigo, strong radial glow, centered link buttons",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "liquid-glass",
    "name": "Liquid Glass",
    "nameZh": "液态玻璃",
    "description": "Liquid glassmorphism — high blur, translucent panels, top highlights, cool cyan-blue, fluid hover",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": true,
      "gradientBg": true,
      "customFonts": true
    }
  },
  {
    "id": "md3",
    "name": "Material 3",
    "nameZh": "Material 3",
    "description": "Material Design 3 baseline — purple seed #6750A4, tonal surfaces, Roboto, 12/16/24 shape, filled first CTA",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": true
    }
  },
  {
    "id": "minimal",
    "name": "Minimal",
    "nameZh": "极简",
    "description": "Ultra-minimal — near-square corners, no shadows/borders, monochrome ink, tight spacing",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "miuix",
    "name": "Miuix",
    "nameZh": "小米 HyperOS",
    "description": "HyperOS / Miuix — exclusive #3482FF, large squircle radii, dense clean surfaces, soft blue elevation",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": true,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "nodeseek",
    "name": "NodeSeek",
    "nameZh": "NodeSeek",
    "description": "Chinese tech-forum rows — cool-gray grid, solid cards, teal accent bar on every link, CJK system fonts",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "qtcool",
    "name": "QT Cool",
    "nameZh": "晴辰酷",
    "description": "Neo-brutal stickers — cream grid, 3px ink stroke, hard 5–8px offset shadow, yellow/orange pops, blue CTA",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "rin",
    "name": "Rin",
    "nameZh": "Rin",
    "description": "openRin/Rin default UI — vibrant rose accent #FC466B, clean neutral surfaces (#f5f5f5 / #1c1c1e), soft shadows, modern edge-native blog aesthetic.",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "xandroid",
    "name": "X Android",
    "nameZh": "X Android",
    "description": "X Android rewrite vibe: solid white/black, neutral gray, #1D9BF0 accent only, ~14px radius, timeline link rows, short transitions",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  }
] as ThemeManifest[];

export const THEME_IDS: string[] = THEME_MANIFESTS.map((m) => m.id);

export function listThemes(): ThemeListItem[] {
  return THEME_MANIFESTS.map((m) => ({
    id: m.id,
    name: m.name,
    nameZh: m.nameZh,
    description: m.description || "",
    features: {
      blur: Boolean(m.features?.blur),
      gradientBg: Boolean(m.features?.gradientBg),
      customFonts: Boolean(m.features?.customFonts),
    },
  }));
}

export function getTheme(id: string | undefined | null) {
  const found = THEME_MANIFESTS.find((m) => m.id === id);
  return found ?? THEME_MANIFESTS.find((m) => m.id === FALLBACK_THEME_ID)!;
}

export function resolveThemeId(id: string | undefined | null, siteDefault?: string | null): string {
  // Legacy aliases
  if (id === "ios27") id = "liquid-glass";
  if (id === "base" || id === "default") id = "aurora";
  if (siteDefault === "ios27") siteDefault = "liquid-glass";
  if (siteDefault === "base" || siteDefault === "default") siteDefault = "aurora";
  if (id && THEME_IDS.includes(id)) return id;
  if (siteDefault && THEME_IDS.includes(siteDefault)) return siteDefault;
  return FALLBACK_THEME_ID;
}

export { FALLBACK_THEME_ID };
