// Scan src/themes/*/theme.json, validate, generate _registry.ts + _bundle.css
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = join(root, "src", "themes");
const FALLBACK = "aurora";

function isDir(p) {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function fail(msg) {
  console.error("[build-themes] " + msg);
  process.exit(1);
}

function validateManifest(raw, dirName) {
  let data;
  try {
    data = JSON.parse(raw);
  } catch {
    fail(dirName + "/theme.json: invalid JSON");
  }
  if (!data || typeof data !== "object") fail(dirName + "/theme.json: must be object");
  if (typeof data.id !== "string" || !data.id) fail(dirName + "/theme.json: missing id");
  if (data.id !== dirName) {
    fail(dirName + '/theme.json: id "' + data.id + '" must equal folder name "' + dirName + '"');
  }
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.id)) {
    fail(dirName + "/theme.json: id must be kebab-case");
  }
  if (typeof data.name !== "string" || !data.name) fail(dirName + ": missing name");
  if (typeof data.nameZh !== "string" || !data.nameZh) fail(dirName + ": missing nameZh");
  if (typeof data.version !== "number" || data.version < 1) {
    fail(dirName + ": version must be number >= 1");
  }
  const tokensFile =
    typeof data.tokensFile === "string" && data.tokensFile ? data.tokensFile : "tokens.css";
  const tokensPath = join(themesDir, dirName, tokensFile);
  if (!existsSync(tokensPath)) fail(dirName + ": tokens file not found: " + tokensFile);
  const features = data.features && typeof data.features === "object" ? data.features : {};
  return {
    id: data.id,
    name: data.name,
    nameZh: data.nameZh,
    description: typeof data.description === "string" ? data.description : "",
    version: data.version,
    tokensFile,
    features: {
      blur: Boolean(features.blur),
      gradientBg: Boolean(features.gradientBg),
      customFonts: Boolean(features.customFonts),
    },
  };
}

const entries = readdirSync(themesDir)
  .filter((name) => !name.startsWith("_"))
  .filter((name) => isDir(join(themesDir, name)))
  .sort();

if (!entries.length) fail("no theme folders found under src/themes/");

const manifests = [];
const cssParts = [];

const defaultCssPath = join(themesDir, "_default.css");
if (!existsSync(defaultCssPath)) fail("missing src/themes/_default.css");
cssParts.push("/* generated by scripts/build-themes.mjs — do not edit */\n");
cssParts.push("/* === _default.css === */\n");
cssParts.push(readFileSync(defaultCssPath, "utf8"));
cssParts.push("\n");

for (const dirName of entries) {
  const jsonPath = join(themesDir, dirName, "theme.json");
  if (!existsSync(jsonPath)) fail(dirName + ": missing theme.json");
  const manifest = validateManifest(readFileSync(jsonPath, "utf8"), dirName);
  manifests.push(manifest);
  const tokens = readFileSync(join(themesDir, dirName, manifest.tokensFile), "utf8");
  cssParts.push("/* === " + dirName + "/" + manifest.tokensFile + " === */\n");
  cssParts.push(tokens);
  cssParts.push("\n");
}

if (!manifests.some((m) => m.id === FALLBACK)) {
  fail('fallback theme "' + FALLBACK + '" is required');
}

const body = JSON.stringify(
  manifests.map((m) => ({
    id: m.id,
    name: m.name,
    nameZh: m.nameZh,
    description: m.description,
    version: m.version,
    tokensFile: m.tokensFile,
    features: m.features,
  })),
  null,
  2,
);

const registryTs =
  "/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand */\n" +
  'import type { ThemeListItem, ThemeManifest } from "./_types";\n' +
  'import { FALLBACK_THEME_ID } from "./_types";\n\n' +
  "export const THEME_MANIFESTS: ThemeManifest[] = " +
  body +
  " as ThemeManifest[];\n\n" +
  "export const THEME_IDS: string[] = THEME_MANIFESTS.map((m) => m.id);\n\n" +
  "export function listThemes(): ThemeListItem[] {\n" +
  "  return THEME_MANIFESTS.map((m) => ({\n" +
  "    id: m.id,\n" +
  "    name: m.name,\n" +
  "    nameZh: m.nameZh,\n" +
  "    description: m.description || \"\",\n" +
  "    features: {\n" +
  "      blur: Boolean(m.features?.blur),\n" +
  "      gradientBg: Boolean(m.features?.gradientBg),\n" +
  "      customFonts: Boolean(m.features?.customFonts),\n" +
  "    },\n" +
  "  }));\n" +
  "}\n\n" +
  "export function getTheme(id: string | undefined | null) {\n" +
  "  const found = THEME_MANIFESTS.find((m) => m.id === id);\n" +
  "  return found ?? THEME_MANIFESTS.find((m) => m.id === FALLBACK_THEME_ID)!;\n" +
  "}\n\n" +
  "export function resolveThemeId(id: string | undefined | null, siteDefault?: string | null): string {\n" +
  "  // Legacy aliases\n" +
  "  if (id === \"ios27\") id = \"liquid-glass\";\n" +
  "  if (id === \"base\" || id === \"default\") id = \"aurora\";\n" +
  "  if (siteDefault === \"ios27\") siteDefault = \"liquid-glass\";\n" +
  "  if (siteDefault === \"base\" || siteDefault === \"default\") siteDefault = \"aurora\";\n" +
  "  if (id && THEME_IDS.includes(id)) return id;\n" +
  "  if (siteDefault && THEME_IDS.includes(siteDefault)) return siteDefault;\n" +
  "  return FALLBACK_THEME_ID;\n" +
  "}\n\n" +
  "export { FALLBACK_THEME_ID };\n";

writeFileSync(join(themesDir, "_registry.ts"), registryTs, "utf8");
writeFileSync(join(themesDir, "_bundle.css"), cssParts.join(""), "utf8");

console.log(
  "[build-themes] ok — " +
    manifests.length +
    " theme(s): " +
    manifests.map((m) => m.id).join(", "),
);
